In [2]:
                                           ''' Importing required libraries'''
    
import selenium
from bs4 import BeautifulSoup
import time
import pandas as pd



# Importing selenium webdriver
from selenium import webdriver

# Importing Exceptions
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException, ElementNotVisibleException, TimeoutException

# importing requests
import requests

#importing regex
import re

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)


from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

### Q1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
1. Rank
2. Name
3. Artist
4. Upload date
5. Views

In [3]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 
time.sleep(2)

# Opening the wikipedia
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

time.sleep(2)
#scraping names of the video
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    name.append('No details available')
    
time.sleep(2)    
#scraping rank of the video
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:#handling no such element exception
    rank.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    rank.append('No details available')

time.sleep(2)
#scraping artist/uploader of the video
artist=[]
try:
    artists=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artists:
        artist.append(i.text)
except NoSuchElementException:#handling no such element exception
    artist.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    artist.append('No details available')
    
time.sleep(2)    
#scraping views of the video
views=[]
try:
    views_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_list:
        views.append(i.text)
except NoSuchElementException:#handling no such element exception
    views.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    views.append('No details available')
    
time.sleep(2)    
#scraping views of the video
upload_date=[]
try:
    upload_date_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_list:
        upload_date.append(i.text)
        
except NoSuchElementException:#handling no such element exception
    upload_date.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    upload_date.append('No details available')
    
time.sleep(2)    
#preparing dataframe
df=pd.DataFrame({"Rank":rank,
                 "Name":name,
                "Uploader/artist":artist,
                "Date of upload":upload_date,
                "Views(in billion)":views})
df

,Rank,Name,Uploader/artist,Date of upload,Views(in billion)
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.35
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.79
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.24
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.65
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.45
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.12
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[21]",Miroshka TV,"February 27, 2018",4.56
7,8.,"""Phonics Song with Two Words""[22]",ChuChu TV,"March 6, 2014",4.52
8,9.,"""Uptown Funk""[23]",Mark Ronson,"November 19, 2014",4.50
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.49
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.37
11,12.,"""Dame Tu Cosita""[30]",El Chombo,"April 5, 2018",3.89
12,13.,"""Wheels on the Bus""[31]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.82
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.66
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.54
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.53
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.52
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.42
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.28
19,20.,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.25
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.25
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.24
22,23.,"""Let Her Go""[41]",Passenger,"July 25, 2012",3.19
23,24.,"""Bailando""[42]",Enrique Iglesias,"April 11, 2014",3.18
24,25.,"""Lean On""[43]",Major Lazer,"March 22, 2015",3.18
25,26.,"""Baa Baa Black Sheep""[44]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.17
26,27.,"""Shake It Off""[45]",Taylor Swift,"August 18, 2014",3.15
27,28.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.12
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.09
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.05

### Q2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/. You need to find following details:

1. Match title (I.e. 1st ODI)
2. Series
3. Place
4. Date
5. Time 

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [3]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 


time.sleep(2)
# Opening the bcci.tv
url = "https://www.bcci.tv/"
driver.get(url)

time.sleep(5)
#going to international fixtures page
fixtures=driver.find_element_by_xpath('//li[@class="nav-item ml-0"]')
try:
    fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))
    
time.sleep(5)
try:
    teams=driver.find_element_by_xpath('//*[@id="fixtures"]/div[2]/div/div[4]/div/div[1]').click()
    slct_team=driver.find_element_by_xpath('//*[@id="fixtures"]/div[2]/div/div[4]/div/div[2]/div[6]').click()
except NoSuchElementException:
    pass

time.sleep(2)   
# make empty lists
match=[] 
series=[]
date=[]
Time=[]
venue = []


#scarping match title
try:                    
    match_title=driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]')
    for i in match_title:
        j=i.text.split('-')[0]
        match.append(j)
except NoSuchElementException:#handling no such element exception
    match.append('No details available')
    
time.sleep(2)
#scarping series title    
try:
    series_title=driver.find_elements_by_xpath('//span[@class="ng-binding"]')
    for s in series_title:
        k=s.text
        series.append(k)
except NoSuchElementException:#handling no such element exception
    series.append("No details Available")
    
time.sleep(2)
#scarping date of match 
try:
    date_title=driver.find_elements_by_xpath('//div[@class="match-card-left match-schedule"]')
    for d in date_title:
        h=d.text
        date.append(h)
except NoSuchElementException:#handling no such element exception
    date.append("No details Available")      
    
time.sleep(2)
#scarping time of the match    
try:
    time_title=driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]')
    for t in time_title:
        g=t.text
        Time.append(g)
except NoSuchElementException:#handling no such element exception
    Time.append("No details Available")    
      
time.sleep(2)
    #scarping match venue    
try:
    place_title=driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]')
    for p in place_title:
        v=p.text.split('-')[1]
        venue.append(v)
except NoSuchElementException:#handling no such element exception
    venue.append("No details Available")
        
time.sleep(2)       
#preparing the dataframe
df=pd.DataFrame({"Match":match,
                "Series":series,
                "Place":venue,
                "Date":date,
                "Time":Time})
df

,Match,Series,Place,Date,Time
0,1st T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"MA Chidambaram Stadium, Chennai",9 JUN 2022,7:30 PM IST
1,2nd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"M Chinnaswamy Stadium, Bengaluru",12 JUN 2022,7:30 PM IST
2,3rd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Vidarbha Cricket Association Stadium, Nagpur",14 JUN 2022,7:30 PM IST
3,4th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Saurashtra Cricket Association Stadium, Rajkot",17 JUN 2022,7:30 PM IST
4,5th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Arun Jaitley Stadium, Delhi",19 JUN 2022,7:30 PM IST

### Q3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
1. Name
2. Description


Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [5]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 
time.sleep(2)

# Opening the guru99.com
url = "https://www.guru99.com/"
driver.get(url)
time.sleep(2)


#clicking on selenium option under testing menu open its tutorial
selenium_link=driver.find_element_by_xpath('//a[@title="Selenium"]')
try:
    selenium_link.click()
except ElementNotInteractableException:          #handling element not clickable exception
    driver.get(selenium_link.get_attribute('href'))
time.sleep(2)

#clicking on Selenium Exception Handling (Common Exceptions List) under Advance Webdriver Stuff!
exception_handle_link=driver.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handle_link.click()
except ElementNotInteractableException:      #handling element not clickable exception
    driver.get(exception_handle_link.get_attribute('href'))              
time.sleep(2)    
    
#scraping exceptions names
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in names[1:]:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)   

#scraping exceptions description
desc=[]
try:
    desc_list=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in desc_list[1:]:
        desc.append(i.text)
except NoSuchElementException:#handling no such element exception
    desc.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Exception_name":name,
                "Description":desc})
df

,Exception_name,Description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

### Q4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
1. Rank
2. State
3. GSDP
4. GSDP
5. Share
6. GDP($ billion)


Note: - From statisticstimes home page you have to reach to economy page through code.

In [12]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 
time.sleep(2)

# Opening the statisticstimes.com
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(2)

#clicking on economy button
economy=driver.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/button')
try:
    economy.click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))
time.sleep(2)


#clicking on gdp of indian states
indian_states=driver.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/div/a[3]')

try:
    indian_states.click()
except ElementNotInteractableException:
    driver.get(indian_states.get_attribute('href')) 
time.sleep(2)

#closing ad popup
try:
    closeAd=driver.find_element_by_xpath('//div[@class="ns-ptzh3-e-14 button-common close-button"]').click()
except NoSuchElementException:
    driver.get('https://www.statisticstimes.com/economy/india-statistics.php')
    

#clicking on indian states
try:
    gdp_states = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
except ElementNotInteractableException:
    driver.get(gdp_states.get_attribute('href')) 
time.sleep(2)


#scraping rank
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    rank.append('No details available')
time.sleep(2)


#scraping States
State=[]
try:
    states=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
    for i in states:
        State.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    State.append('No details available')
time.sleep(2)


#scraping GSDP(19-20)
GSDP_20=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in info:
        GSDP_20.append(i.text)
except NoSuchElementException:           #handling no such element exception
    GSDP_20.append('No details available')
time.sleep(2)    
    
#scraping GSDP(18-19)
GSDP_19=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
    for i in info:
        GSDP_19.append(i.text)
except NoSuchElementException:        #handling no such element exception
    GSDP_19.append('No details available')
time.sleep(2)

#scraping share (18-19)
share=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
    for i in info:
        share.append(i.text)
except NoSuchElementException:          #handling no such element exception
    share.append('No details available')
time.sleep(2)

#scraping GDP(billion$)
GDP_billion=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")
    for i in info:
        GDP_billion.append(i.text)
except NoSuchElementException:            #handling no such element exception
    GDP_billion.append('No details available')
time.sleep(2)

#creatng dataframe
df=pd.DataFrame({'Rank':rank,
                'State':State,
                'GSDP(19-20)':GSDP_20,
                'GSDP(18-19)':GSDP_19,
                'Share(18-19)':share,
                'GDP(Billion_$)':GDP_billion})
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP(Billion_$)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

### Q5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
1. Repository title
2. Repository description
3. Contributors count
4. Language used

In [2]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 
time.sleep(2)

# Opening the github
url = "https://github.com/explore/"
driver.get(url)

# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls
repos=driver.find_elements_by_xpath('//a[@class="text-bold wb-break-word"]')
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2)    
    
#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements_by_xpath('//h3[@class="f3 color-fg-muted text-normal lh-condensed"]')
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    

for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
     #scraping repositories discription
    try:          
        repo_desc.append(driver.find_element_by_xpath('//div[@class="Box-body px-5 pb-5"]').text)
    except:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

,Title,Description,Contributors_count,Language_used
0,CodeEditApp / CodeEdit,CodeEdit macOS App\n⚠️ CodeEdit is currently i...,21,"[Swift, Shell]"
1,microsoft / routeros-scanner,RouterOS Scanner\nForensics tool for Mikrotik ...,3,[Python]
2,ToolJet / ToolJet,ToolJet is an open-source low-code framework t...,133,"[JavaScript, TypeScript, SCSS, Shell, EJS, Doc..."
3,pedroslopez / whatsapp-web.js,whatsapp-web.js\nA WhatsApp API client that co...,65,"[JavaScript, Shell]"
4,ocornut / imgui,Dear ImGui\n(This library is available under a...,281,"[C++, C, Objective-C++, Objective-C, GLSL, GDB]"
5,Dreamacro / clash,Clash\nA rule-based tunnel in Go.\nFeatures\nL...,75,[Go]
6,bitcoin / bitcoin,Bitcoin Core integration/staging tree\nhttps:/...,855,"[C++, Python, C, M4, Shell, Makefile]"
7,arthurspk / guiadevbrasil,📚 GUIA EXTENSO DE PROGRAMAÇÃO\n⚠️ AVISO IMPORT...,25,[No languages used]
8,lxgr-linux / pokete,Pokete -- Grey Edition\nSee more example pics\...,2,"[Python, Shell]"
9,PKUFlyingPig / cs-self-learning,CS自学指南\nEveryone should enjoy CS if you have a...,23,[HTML]
10,johnthebrit / CertificationMaterials,Certification Materials\nA collection of mater...,No details available,[No languages used]
11,freddier / hyperblog,Hyperblog 💚\nUn blog increíble para el curso d...,278,"[HTML, CSS]"
12,openmlsys / openmlsys-zh,机器学习系统：设计和实现\n本开源项目试图给读者讲解现代机器学习系统的设计原理和实现经验。\...,21,"[TeX, Python, Shell]"
13,kabinspace / AstroVim,AstroVim\nAstroVim is an aesthetic and feature...,11,"[Lua, Vim Script]"
14,rust-lang / rust,The Rust Programming Language\nThis is the mai...,"3,682","[Rust, Python, JavaScript, Shell, Makefile, C++]"
15,public-apis / public-apis,Public APIs\nA collective list of free APIs fo...,"1,269","[Python, Shell]"
16,RanKKI / LawRefBook,在线版\n中国法律\n根据《中华人民共和国著作权法》第五条，本作品不适用于该法。如不受其他法...,3,"[Swift, Python, Ruby]"
17,vnpy / vnpy,"VeighNa - By Traders, For Traders.\n💬 Want to ...",117,[Python]
18,coolsnowwolf / lede,欢迎来到Lean的Openwrt源码仓库！\nEnglish\n如何编译自己需要的 Open...,289,"[C, Makefile, Shell, Roff, Perl, M4]"
19,google-research / kubric,Kubric\nA data generation pipeline for creatin...,8,"[Python, Makefile, Dockerfile, Shell]"
20,2dust / v2rayN,"v2rayN\nA V2Ray client for Windows, support Xr...",17,[C#]
21,TheAlgorithms / Rust,The Algorithms - Rust\nAll algorithms implemen...,93,"[Rust, Python]"
22,dair-ai / ML-Course-Notes,🎓 ML Course Notes\nA place to collaborate and ...,No details available,[No languages used]
23,trustwallet / assets,Trust Wallet Assets Info\nOverview\nTrust Wall...,"3,487","[Go, Makefile]"
24,home-assistant / core,Home Assistant\nOpen source home automation th...,"2,833",[Python]

### Q6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
1. Song name
2. Artist name
3. Last week rank
4. Peak rank
5. Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [3]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 

# Opening the billboard
url = "https://www.billboard.com/charts/hot-100/"
driver.get(url)
time.sleep(3)

In [4]:
#scraping song names
song_name=[]
try:
    names=driver.find_elements_by_xpath('//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet"]')
    for i in names:
        song_name.append(i.text)
except NoSuchElementException:       #handling no such element exception
    song_name.append('No details available')
time.sleep(2)

try:
    name=driver.find_elements_by_xpath('//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]')
    for j in name:
        song_name.append(j.text)
except NoSuchElementException:
    song_name.append('No details available')
time.sleep(2)


#scraping artist_names
artist_name=[]
try:
    artnames=driver.find_elements_by_xpath('//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet"]')
    for k in artnames:
        artist_name.append(k.text)
except NoSuchElementException:       #handling no such element exception
    song_name.append('No details available')
time.sleep(2)

try:
    artname=driver.find_elements_by_xpath('//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
    for l in name:
        artist_name.append(l.text)
except NoSuchElementException:
    artist_name.append('No details available')
time.sleep(2)


#scraping last week rank
last_week_rank=[]
try:
    lastranks=driver.find_elements_by_xpath('//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]')
    for m in lastranks:
        last_week_rank.append(m.text)
except NoSuchElementException:        #handling no such element exception
    last_week_rank.append('No details available') 
time.sleep(2)
last_week_rank=last_week_rank[::2]


#scraping peak rank
peak_rank=[]
try:
    ranks=driver.find_elements_by_xpath('//li[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max"]')
    for n in ranks:
        peak_rank.append(n.text)
except NoSuchElementException:      #handling no such element exception
    peak_rank.append('No details available')
time.sleep(2)
peak_rank=peak_rank[1::2]


#scraping weeks on chart
weeks=[]
try:
    week_count=driver.find_elements_by_xpath('//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]')
    for e in week_count:
        weeks.append(e.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('No details available')
time.sleep(2)
weeks=weeks[1::2]

#creating dataframe
df=pd.DataFrame({'Song_Name':song_name,
                'Artist_Name':artist_name,
                'Last_week_rank':last_week_rank,
                'Peak':peak_rank,
                'Weeks_on_chart':weeks})
df

,Song_Name,Artist_Name,Last_week_rank,Peak,Weeks_on_chart
0,Heat Waves,Glass Animals,1,1,61
1,Stay,Stay,5,1,36
2,Super Gremlin,Super Gremlin,3,3,19
3,abcdefu,abcdefu,4,3,17
4,We Don't Talk About Bruno,We Don't Talk About Bruno,2,1,12
...,...,...,...,...,...
95,By Your Side,By Your Side,86,58,16
96,Waiting On A Miracle,Waiting On A Miracle,83,48,11
97,I Hate YoungBoy,I Hate YoungBoy,81,79,3
98,City Of Gods,City Of Gods,90,46,5
99,Closer,Closer,99,89,5

### Q7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
1. Name
2. Designation
3. Company
4. Skills they hire for
5. Location


Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [7]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 
time.sleep(2)

# Opening the naukri.com
url = "https://www.naukri.com/searching-recruiters"
driver.get(url)
time.sleep(2)

#accesing search bar
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

#clicking on search button
button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

#scrapping names
name=[]
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:           #handling no such element exception
    name.append('No details available')
time.sleep(2)


#scrapping designation
designation=[]
try:
    designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
    for i in designation_list:
        designation.append(i.text)
except NoSuchElementException:        #handling no such element exception
    designation.append('No details available')
time.sleep(2)


#scrapping company names
company=[]
try:
    companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in companies:
        company.append(i.text)
except NoSuchElementException:#handling no such element exception
    company.append('No details available')
time.sleep(2)

#scrapping location names
location=[]
soup=BeautifulSoup(driver.page_source,'html.parser')
l=soup.find_all('div',attrs={'vcard'})
for i in l:
    try:
        location.append(i.find('small').text)
    except AttributeError :
        location.append("No details available")
time.sleep(2)

#skills they hire for
skill=[]
try:
    skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skills:
        skill.append(i.text)
except NoSuchElementException:        #handling no such element exception
    skill.append('No details available')
time.sleep(2)    
        
#creating dataframe
df=pd.DataFrame({'Name':name,
                'Designation':designation,
                'Company':company,
                "Location":location,
                'Skills I hire':skill})
df

,Name,Designation,Company,Location,Skills I hire
0,Garima Sharma,Recruitment Consultant,Premium-Jobs,Delhi,Not Specified
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,Chirag Agarwal,Company Recruiter,Knoldus software LLP,Noida,"javascript, Ui Development, angularjs, React.j..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
5,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
7,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
9,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
10,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
11,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
12,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
13,Daniel Vaz,Senior Consultant Trading Technology...,Klickto Search,Mumbai,High Frequency Trading firms &amp; Hedge Funds
14,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
15,Sunny Sharma,Managing Director - HR,Western Service Providers,Mumbai,"Software Professionals, Engineering, Technical..."
16,Sagar Lama,Company HR Manager,AdView,Bengaluru / Bangalore,"Full Stack Developers, Product Manager, Data S..."
17,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
18,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
19,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
20,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
21,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
22,Rajni,Team Leader HR Operations,Red Ore Services Pvt Ltd.,Delhi,"Analytics, Machine Learning, Data Science, Etl..."
23,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
24,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
25,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
26,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
27,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
28,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
29,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
30,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
31,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
32,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
33,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
34,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
35,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
36,Sunil Vedula,CEO,Nanoprecise Sci Corp,No details available,"Signal Processing, Machine Learning, Neural Ne..."
37,Avodha,Business Development Associate,Nikitha Palaparthi,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
38,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
39,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
40,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
41,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
42,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
43,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
44,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
45,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
46,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
47,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
48,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
49,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."

### Q8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
1. Book name
2. Author name
3. Volumes sold
4. Publisher
5. Genre

In [8]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 
time.sleep(2)

# Opening the theguardian.com
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

#scrapping book names
book_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:              #handling no such element exception
    book_name.append('No details available')
time.sleep(2)

#scrapping author names
author_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('No details available')
time.sleep(2)


#scrapping Sale
Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('No details available')
time.sleep(2)    

#scrapping publisher
publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('No details available')
time.sleep(2)

#scrapping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Book_name":book_name,
                "Author_name":author_name,
                'Volume sold':Sale,
                'Publisher':publisher,
                'Genre':genre})
df

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

### Q9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
1. Name
2. Year span
3. Genre
4. Run time
5. Ratings
6. Votes

In [9]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(2)

# scraping name of webseries
name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)


# scraping year of release
years=[]
try:
    span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in span:
        years.append(i.text)
except NosuchElementException:#handling no such element exception
    years.append('No details available')
time.sleep(2)


# scraping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)


# scraping run_time
run_time=[]
try:
    info=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in info:
        run_time.append(i.text)
except NoSuchElementException:#handling no such element exception
    run_time.append('No details available')
time.sleep(2)


# scraping rating
rating=[]
try:
    info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in info:
        rating.append(i.text)
except NoSuchElementException:#handling no such element exception
    rating.append('No details available')
time.sleep(2)

# scraping votes
votes=[]
try:
    info=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in info:
        votes.append(i.text)
except NoSuchElementException:#handling no such element exception
    votes.append('No details available')
time.sleep(2)


#creating dataframe
df=pd.DataFrame({"Name":name,
                "years":years,
                "Genre":genre,
                "Run_time":run_time,
                "Rating":rating,
                "Votes":votes})
df

,Name,years,Genre,Run_time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,966,579"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"973,943"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.3,"936,919"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"280,231"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.7,"240,323"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.6,"48,088"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"58,788"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.2,"186,997"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"39,655"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"223,694"

### Q10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
1. Dataset name
2. Data type
3. Task
4. Attribute type
5. No of instances
6. No of attribute
7. Year


Note: - from the home page you have to go to the ShowAllDataset page through code.

In [10]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:\Users\Rohit\Documents\chrome_webdriver\chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(2)


#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping dataset names
data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset names
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

                                                  ----- --:-- -----